sectors = [
    "Gesamt (ohne E1 - E7)",
    "Produzierender Bereich Gesamt",
    "Transport Gesamt",
    "Sonstige Wirtschaftsbereiche Gesamt",
    "Eisen- und Stahlerzeugung",
    "Chemie und  Petrochemie",
    "Nicht Eisen Metalle",
    "Steine und Erden, Glas",
    "Fahrzeugbau",
    "Maschinenbau",
    "Bergbau",
    "Nahrungs- und Genußmittel, Tabak",
    "Papier und Druck",
    "Holzverarbeitung",
    "Bau",
    "Textil und Leder",
    "Sonst. Produzierender Bereich",
    "Eisenbahn",
    "Sonstiger Landverkehr",
    "Transport in Rohrfernleitungen",
    "Binnenschiffahrt",
    "Flugverkehr",
    "Offentliche und Private Dienstleistungen",
    "Private Haushalte",
    "Landwirtschaft",
]

energy_sources_99_plus = [
    "Steinkohle",
    "Braunkohle",
    "Koks",
    "Petrolkoks",
    "Heizöl",
    "Gasöl für Heizzwecke ",
    "Diesel",
    "Benzin",
    "Petroleum",
    "Flüssiggas",
    "Erdgas",
    "Elektrische Energie",
    "Fernwärme",
    "Scheitholz",
    "Biogene Brenn- und Treibstoffe",
    "Brennbare Abfälle",
    "Sonstige ET",
    "Umgebungswärme etc.",
    "Gichtgas",
    "Kokereigas",
    "Brenntorf",
    "Insgesamt",
]

energy_sources_93_98 = [
    "Steinkohle",
    "Braunkohle",
    "Sonstige ET",
    "Koks",
    "Brenntorf",
    "Benzin",
    "Petroleum",
    "Diesel",
    "Gasöl für Heizzwecke ",
    "Heizöl",
    "Flüssiggas",
    "Petrolkoks",
    "Erdgas",
    "Gichtgas",
    "Kokereigas",
    "Brennbare Abfälle",
    "Scheitholz",
    "Biogene Brenn- und Treibstoffe",
    "Umgebungswärme etc.",
    "Fernwärme",
    "Elektrische Energie",
    "Insgesamt",
]

energy_sources_nea_df = [
    "Steinkohle",
    "Braunkohle",
    "Koks",
    "Petrolkoks",
    "Heizöl",
    "Gasöl für Heizzwecke ",
    "Diesel",
    "Benzin",
    "Petroleum",
    "Flüssiggas",
    "Erdgas",
    "Elektrische Energie",
    "Fernwärme",
    "Scheitholz",
    "Biogene Brenn- und Treibstoffe",
    "Brennbare Abfälle",
    "Braunkohlenbriketts",
    "Umgebungswärme etc.",
    "Gichtgas",
    "Kokereigas",
    "Brenntorf",
    "Insgesamt",
]

energy_sources_nea_df_reindex = [
    "Steinkohle",
    "Braunkohle",
    "Braunkohlenbriketts",
    "Koks",
    "Petrolkoks",
    "Heizöl",
    "Gasöl für Heizzwecke ",
    "Diesel",
    "Benzin",
    "Petroleum",
    "Flüssiggas",
    "Erdgas",
    "Gichtgas",
    "Kokereigas",
    "Scheitholz",
    "Biogene Brenn- und Treibstoffe",
    "Brennbare Abfälle",
    "Brenntorf",
    "Umgebungswärme etc.",
    "Fernwärme",
    "Elektrische Energie",
    "Insgesamt",
]

# energy_sources_93_98 = [
#     "Steinkohle",
#     "Braunkohle",
#     "Braunkohlenbriketts",
#     "Koks",
#     "Brenntorf",
#     "Benzin",
#     "Leucht- und Flugpetroleum",
#     "Gasöl (Diesel)",
#     "Gasöl für Heizzwecke ",
#     "Heizöl",
#     "Flüssiggas",
#     "Sonst. Produkte der Erdölverarb.  ",
#     "Erdgas",
#     "Gichtgas",
#     "Kokereigas",
#     "Brennbare Abfälle",
#     "Scheitholz",
#     "Biogene Brenn- und Treibstoffe",
#     "Umgebungswärme etc.",
#     "Fernwärme",
#     "Elektrische Energie",
#     "Insgesamt",
# ]

energy_usage_types = [
    "Raumheizung und Klimaanlagen",
    "Dampferzeugung",
    "Industrieöfen",
    "Standmotoren",
    "Traktion",
    "Beleuchtung und EDV",
    "Elektrochemische Zwecke",
    "Summe",
]
